version: '3.8'
services:
  myweb:
    build: .
    depends_on:
      - mydb
    volumes:
      - ./:/code
    ports:
      - '8000:80'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@mydb/sample_db

  mydb:
    container_name: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sample_db
    image: postgres:16-alpine

volumes:
  postgres_data:
