version: '3.5'
services:
  myweb:
    build: .
    depends_on:
      - mydb
    volumes:
      - ./:/code:ro
    ports:
      - "8000:80"

  mydb:
    container_name: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sample_db
    image: postgres:16-alpine

volumes:
   postgres_data:
